# Generated by Django 2.2.2 on 2019-09-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_remove_product_no_of_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('selling_price', models.IntegerField(verbose_name='selling_price')),
                ('total', models.FloatField(verbose_name='total')),
                ('payment', models.IntegerField()),
                ('description', models.TextField()),
                ('sub_total', models.FloatField()),
                ('balance', models.FloatField()),
                ('modes', models.CharField(choices=[('0', 'CASH'), ('1', 'CHEQUE'), ('2', 'OTHER')], max_length=2)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'SalesDetails',
                'db_table': 'sales_db',
            },
        ),
    ]
