# Generated by Django 2.2.2 on 2019-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='product_name')),
                ('category_name', models.CharField(choices=[('0', 'Electronics'), ('1', 'Accessories')], max_length=2)),
                ('no_of_product', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'product_db',
            },
        ),
    ]
