# Generated by Django 2.2.2 on 2019-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='product_name')),
                ('category_name', models.TextField(unique=True, verbose_name='category_name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category_db',
            },
        ),
    ]
